### ISSUE TITLE
error at observed average difference code

### ISSUE THREAD

**Issue by LauraMariaGrawehr** [DeAngelisA/ISSS23#10]
Hello everybody :)
I'm struggling with the code for the observed average difference.
First I had this code, then R replied that: Fehler in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : nicht-numerisches Argument für binären Operator
**obs_avg_diff <- dat %>%
  group_by(T) %>%
  summarize(average = mean(diff(Y)))**

So then I transformed Y into a numeric variable and it replied the same error?!

**obs_avg_diff <- dat %>% 
  group_by(T) %>%  
  summarize(average = as.numeric(mean(diff(y))))**

Can anyone give me a hint?

**Comment by DeAngelisA** [comment]
@LauraMariaGrawehr : good try! 
I think the problem is with `diff()`, leave that out and it should work.

**Comment by LauraMariaGrawehr** [comment]
@DeAngelisA 
Thanks for your response. Unfortunately R replies a new error message:
**argument is not numeric or logical: returning NAargument is not numeric or logical: returning NA**

**Comment by DeAngelisA** [comment]
@LauraMariaGrawehr : I cannot replicate the error, so try some debugging. A couple of hints: 1. you can convert to numeric only character variables that actually have numeric digits (i.e., compare `as.numeric(c("yes", "no"))` and as.numeric(c("1", "0")). 2. You usually want to convert to numeric *before* computing the mean, rather than *after*.
