### ISSUE TITLE
PS3: Exercise 3.1.5

### ISSUE THREAD

**Issue by LinhRamirez** [DeAngelisA/ISSS23#14]
Dear all :) 

**I am facing issues with the following point on exercise 3.1.5**. The dependent variable `res_price` is a function of `age`, `income` plus the `error` term: on average, older and high-income consumers can spend more to buy your e-bike (feel free to choose how much more). Problem: I am not understanding well how I can set the parameters. How do I know which numbers I have to add/multiple/subtract from my variables? Of course, I understood that we have to do trial/error and find out what makes sense, but how do I know if I should take 0.01 and then 0.3 (like in the example of PS2).

This would be an example of the PS2, in which andrea set the parameters:

```r
#y0i: overall health without insurance
#here I set a lot of parameters after some trial and error
y0 = -19 + 0.9 * age - 0.01 * age_sqrd - 0.3 * educ_high_school + 0.2 * educ_college + 0.6 * educ_grad_school + error
```

I also found this simple example on [this page](https://towardsdatascience.com/generate-simulated-dataset-for-linear-model-in-r-469a5e2f4c2e), but also here I am really confused with the parameters. 
I am pretty sure I am overthinking this step.

```r
set.seed(1234)

# Linear Regression
# Generate the independent variable and the error
x1=rnorm(100,50,9)
x2=rnorm(100,200,64)
error=rnorm(100,0,16)

# Generate the dependent variable (b0=150, b1=-4, b2=2.5)
y1 = 150 - (4*x1) + (2.5*x2) + error

# create the model
m1=lm(y1~x1+x2)
summary(m1)
autoplot(m1)
```

Thanks for a hint / help, very much appreciated :)

**Comment by LinhRamirez** [comment]
I also found this simple example on the page (https://towardsdatascience.com/generate-simulated-dataset-for-linear-model-in-r-469a5e2f4c2e), but also here I am really confused with the parameters. I am pretty sure I am overthinking this step.

set.seed(1234)

_Linear Regression
Generate the independent variable and the error_
x1=rnorm(100,50,9)
x2=rnorm(100,200,64)
error=rnorm(100,0,16)
_Generate the dependent variable (b0=150, b1=-4, b2=2.5)_
y1=150-(4*x1)+(2.5*x2)+error
_create the model_
m1=lm(y1~x1+x2)
summary(m1)
autoplot(m1)

**Comment by DeAngelisA** [comment]
@LinhRamirez: this is about understanding that these parameters reflect the magnitude of the effect. So, finding a good value means to think about the measurement units. In general, saying for example: `y = 1 * x` means that one unit increase in `x` leads to a one-unit increase in `y`. However, when you simulate data you want to think about plausible values. So if, for example, now `y = yearly income in CHF` and `x = {0: no master degree; 1: master degree or above}`, then one may think that an average income is plausibly in the order of tens of thousands of units (i.e., CHF), and having a master degree will probably increase this value by e.g. 10,000. So, a plausible value may be `yearly_income = 10000 * x`. 

Note: we do not find such high values of the parameters very practical, and for this reason we often re-scale the variables to have more readable parameters. For instance, in this case we may express the yearly income in `1,000CHF` instead of unit Swiss francs by dividing by 1000. Here would be some more elaborate code for this example: 
```r
library(tidyverse)

# You can also set the parameters storing the values:
my_interc_param <-  1
my_slope_param <- 10000

set.seed(1234)

dat <- tibble(
  x = sample(x = 0:1, size = 1000, replace = TRUE), 
  e = rnorm(n = 1000, mean = 0, sd = 20000)
) %>% 
  mutate(
    # y in unit CHF:
    y = my_interc_param + my_slope_param * x + e, 
    
    # y in unit 1,000CHF:
    y_1000 = y / 1000
  )

fit1 <- lm(y ~ x, data = dat)
fit2 <- lm(y_1000 ~ x, data = dat)
stargazer::stargazer(fit1, fit2, type = "text")

===========================================================
                                   Dependent variable:     
                               ----------------------------
                                      y           y_1000   
                                     (1)           (2)     
-----------------------------------------------------------
x                               8,607.620***     8.608***  
                                 (1,200.255)     (1.200)   
                                                           
Constant                           444.158        0.444    
                                  (836.742)      (0.837)   
                                                           
-----------------------------------------------------------
Observations                        1,000         1,000    
R2                                  0.049         0.049    
Adjusted R2                         0.048         0.048    
Residual Std. Error (df = 998)   18,970.260       18.970   
F Statistic (df = 1; 998)         51.430***     51.430***  
===========================================================
Note:                           *p<0.1; **p<0.05; ***p<0.01
```


Note how the coefficients (both the estimates and the standard errors) are re-scaled comparing `fit2` to `fit1`. 

Finally, if I inspect the `y` (or `y_1000`) variable: 
```r
> summary(dat$y)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -58609   -7655    4307    4627   17994   64117
```

I note that the minimum is `-58609`, but a negative yearly income is totally implausible, and so then I will adjust the intercept to shift everything upwards. Hope this helps! ;)

**Comment by LinhRamirez** [comment]
Thank you Andrea, that really helped a lot! :)
