### ISSUE TITLE
Measuring performance of for loop - strange results

### ISSUE THREAD

**Issue by alestraehl** [DeAngelisA/ISSS23#29]
Hi all,
In this week's assignment, there was a task to measure the for loop performance depending on whether we allocate space first or not (part 4, page 317, Exercise 4).
I did this with the following code:
```
slow <- function(x) {
  t1 <- Sys.time()
  output <- vector("integer", 0)
  for (i in seq_along(x)) {
    output <- c(output, lengths(x[[i]]))
  }
  t2 <- Sys.time()
  T1 <- as.numeric(t2) - as.numeric(t1)
  return(T1)
}

fast <- function(x, lx) {
  t3 <- Sys.time()
  output <-vector("integer", lx)
  for (i in seq_along(x)) {
    output <- c(output, lengths(x[[i]]))
  }
  t4 <- Sys.time()
  T2 <- as.numeric(t4) - as.numeric(t3)
  return(T2)
}

```
Then I pass different arguments, however as you can see in the comments, the time is not as I expect: I expect fast < slow.

```
x = 1:5
lx = length(x)
slow(x) # [1] 2.717972e-05
fast(x, lx) # [1] 1.072884e-05

y = 1:1000
ly = length(y)
slow(y) # [1] 0.004562378
fast(y, ly) # [1] 0.002670527

z = 1:90000
lz = length(z)
slow(z) # [1] 3.894891
fast(z, lz) # [1] 12.16922
```
Does anyone have an idea what could be the problem here?

**Comment by DeAngelisA** [comment]
@alestraehl: since nobody else replies I give it my shot!
Your expectation that the `fast` function should be quicker than the `slow` one because it pre-allocates space true. Making a vector larger in a loop (as in `slow`) requires much more time because every time it has to repeat the memory allocation process! 

However, there seems to be a mistake in the implementation of the `fast` function. Both functions are actually doing almost the same thing. In the `fast` function, even though space is pre-allocated, the vector output is still growing inside the loop: 
`output <- c(output, lengths(x[[i]]))`

To take full advantage of pre-allocation, you should change the code, here is one possibility:
```r
fast <- function(x, lx) {
  t3 <- Sys.time()
  output <- vector("integer", lx)
  for (i in seq_along(x)) {
    output[i] <- lengths(x[[i]]) # Filling the pre-allocated vector
  }
  t4 <- Sys.time()
  T2 <- as.numeric(t4) - as.numeric(t3)
  return(T2)
}
```
Remember, the performance gain might not be noticeable for small-sized vectors, but as the size grows, the benefits of pre-allocation should become more apparent. Hope this helps!

**Comment by alestraehl** [comment]
Oh, thank you, that actually helps! With short vectors, sometimes the result is still "the wrong way around", though I assume this is due to the precision of the operation itself on the computer. For 9000 elements, the slow() function now takes 3 seconds, while the fast() function is still 0.04 seconds! And still runs in less than a second for 900'000 elements.
